config/routes.rb
Rails.application.routes.draw do
  get 'logout', to: 'logins#destroy', as: :logout

  resources :logins, only: [:new, :create]
  resources :registrations, only: [:new, :create]
  resources :posts

  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true
    validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login

    private

    def require_login
        @user = User.find_by(id: session[:user_id])
        redirect_to new_login_path unless @user
    end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    user = User.find_by(id: session[:user_id])
    redirect_to new_login_path unless user
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to posts_path if user
    @user = User.new
  end

  def create
    @user = User.find_by(login_params)
    if @user
      session[:user_id] = @user.id
      redirect_to posts_path
    else
      @user = User.new
      flash.now[:alert] = "Email or password is wrong!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy 
    session.clear
    redirect_to root_url, notice: "Logged out."
  end

  private
    def login_params
      params.require(:user).permit(:email, :password)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find_by(id: session[:user_id])
    @posts = Post.includes(:user).references(:user).all
  end

  def new
    @post = Post.new
  end

  def create
    post = Post.new(post_params)

    user = User.find_by(id: session[:user_id])
    post.user_id = user.id

    if post.save
      redirect_to posts_path
    else
      @post = Post.new
      flash.now[:alert] = "Couldn't save the post!"
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @post = Post.find(params[:id])
  end
  
  def edit
    @post = Post.find(params[:id])
  end

  def update
    user = User.find_by(id: session[:user_id])

    # make sure user is the author
    post = Post.find(params[:id])
    if post.user_id != user.id
      redirect_to post_path(post), alert: "Unauthorized!"
    elsif post.update(title: params[:post][:title], body: params[:post][:body])
      redirect_to post_path(post)
    else
      flash.now[:alert] = "Couldn't save the post!"
      render :edit, status: :unprocessable_entity
      return
    end
  end

  def destroy
    @post= Post.find(params[:id])
    @post.destroy()
   
    redirect_to root_path
  end

  private 
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  def new
    user = User.find_by(id: session[:user_id])
    redirect_to posts_path if user
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to new_login_path
    else
      flash[:alert] = "Couldn't save the user!"
      render :new, status: :unprocessable_entity
    end
  end

  private 
    def user_params
      params.require(:user).permit(:email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/dashboards/index.html.erb
<h1>Welcome</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if @user %>
      <%= link_to "Sign out", logout_path %>
    <% else %>
      <%= link_to "Log in", new_login_path %>
      <%= link_to "Register", new_registration_path %>
    <% end %>
    <div><%= notice %></div>
    <div><%= alert %></div>
    <%= yield %>
  </body>
</html>

app/views/logins/new.html.erb
<h1>Log in</h1>

<%= form_with model: @user, url: logins_path do |form| %>
  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Log in" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Update Post</h1>

<%= form_with model: @post, url: post_path(@post), method: "patch" do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>
  <div>
    <%= form.submit "Update" %>
  </div>
<% end %>

<%= link_to "Delete Post", post_path(@post), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }%>
<%= link_to "Cancel", post_path(@post) %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>

<% if @user %>
  <%= link_to "New Post", new_post_path %>
<% end %>

<br><br>

<% if @posts.length > 0 %>
  <table>
    <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post_path(post)  %></td>
        <td><strong>by:</strong><%= post.user.email %></td>
        <td><strong>date:</strong><%= post.updated_at %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
<p>There are no posts yet. Login or signup to make a post</p>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_with model: @post, url: posts_path do |form| %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_field :body %>
  </div>
  <div>
    <%= form.submit "Post!" %>
  </div>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>

<% if @user && @user.id == @post.user_id %>
    <%= link_to "Edit Post", edit_post_path(@post) %>
<% end %>
<%= link_to "Back", posts_path %>